### ISSUE TITLE
Issues when generation

### ISSUE THREAD

**Issue by waterluck** [RUCAIBox/Language-Specific-Neurons#9]
Hi Team, Thanks for sharing your great work!

When executing alone with the `generation.py` using those neuron files you provided, like  `LLaMA-2-7B.neuron.pth`, I got the error below error triggered by `outputs = model.generate(texts, sampling_params)`. Do you have any idea how to fix this, or are there any other requirements needed?   Thanks for your help! 

I'm using `vllm=0.2.7`. The error details are as follows. 

```
../aten/src/ATen/native/cuda/IndexKernel.cu:135: operator(): block: [1,0,0], thread: [28,0,0] Assertion `idx >= -self_dim_size && idx < self_dim_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:135: operator(): block: [1,0,0], thread: [29,0,0] Assertion `idx >= -self_dim_size && idx < self_dim_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:135: operator(): block: [1,0,0], thread: [30,0,0] Assertion `idx >= -self_dim_size && idx < self_dim_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:135: operator(): block: [1,0,0], thread: [31,0,0] Assertion `idx >= -self_dim_size && idx < self_dim_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/work00/sue/Language-Specific-Neurons/generation.py", line 103, in <module>
    outputs = model.generate(texts, sampling_params)
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 165, in generate
    return self._run_engine(use_tqdm)
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 185, in _run_engine
    step_outputs = self.llm_engine.step()
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 628, in step
    all_outputs = self._run_workers(
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 795, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/vllm/worker/worker.py", line 189, in execute_model
    output = self.model_runner.execute_model(seq_group_metadata_list,
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/vllm/worker/model_runner.py", line 453, in execute_model
    hidden_states = model_executable(
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 286, in forward
    hidden_states = self.model(input_ids, positions, kv_caches,
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 254, in forward
    hidden_states, residual = layer(
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 218, in forward
    hidden_states = self.mlp(hidden_states)
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work00/sue/Language-Specific-Neurons/generation.py", line 72, in llama_forward
  activation.index_fill_(2, mask, 0)                                                                                                                                                [22/949]
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[E ProcessGroupNCCL.cpp:916] [Rank 0] NCCL watchdog thread terminated with exception: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x1187c01a9617 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/to
rch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x1187c016498d in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.
9-new/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x1187c0265128 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-ne
w/lib/python3.9/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x80 (0x11873f357250 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3
.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0x58 (0x11873f35b078 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/
lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x250 (0x11873f371910 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/lib/l
ibtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x78 (0x11873f371c18 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/lib/l
ibtorch_cuda.so)
frame #7: <unknown function> + 0xdc253 (0x118783adc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #8: <unknown function> + 0x94ac3 (0x1187c1694ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x1187c1726850 in /lib/x86_64-linux-gnu/libc.so.6)

[2024-09-06 11:56:24,068 E 3922458 3925635] logging.cc:108: Unhandled exception: St13runtime_error. what(): [Rank 0] NCCL watchdog thread terminated with exception: CUDA error: device-side a
ssert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x1187c01a9617 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/to
rch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x1187c016498d in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.
9-new/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x1187c0265128 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-ne
w/lib/python3.9/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x80 (0x11873f357250 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3
.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0x58 (0x11873f35b078 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/
lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x250 (0x11873f371910 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/lib/l
ibtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x78 (0x11873f371c18 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/lib/l
ibtorch_cuda.so)
frame #7: <unknown function> + 0xdc253 (0x118783adc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #8: <unknown function> + 0x94ac3 (0x1187c1694ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x1187c1726850 in /lib/x86_64-linux-gnu/libc.so.6)

[2024-09-06 11:56:24,098 E 3922458 3925635] logging.cc:115: Stack trace:
[2024-09-06 11:56:24,068 E 3922458 3925635] logging.cc:108: Unhandled exception: St13runtime_error. what(): [Rank 0] NCCL watchdog thread terminated with exception: CUDA error: device-side a
ssert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x1187c01a9617 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/to
rch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x1187c016498d in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.
9-new/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x1187c0265128 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-ne
w/lib/python3.9/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x80 (0x11873f357250 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3
.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0x58 (0x11873f35b078 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/
lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x250 (0x11873f371910 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/lib/l
ibtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x78 (0x11873f371c18 in /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/lib/l
ibtorch_cuda.so)
frame #7: <unknown function> + 0xdc253 (0x118783adc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #8: <unknown function> + 0x94ac3 (0x1187c1694ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x1187c1726850 in /lib/x86_64-linux-gnu/libc.so.6)

[2024-09-06 11:56:24,098 E 3922458 3925635] logging.cc:115: Stack trace:
 /home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/ray/_raylet.so(+0x108308a) [0x1186c99b408a] ray::operator<<()
/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/ray/_raylet.so(+0x1086312) [0x1186c99b7312] ray::TerminateHandler()
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xae20c) [0x118783aae20c]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xae277) [0x118783aae277]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xae1fe) [0x118783aae1fe]
/home/sue-xie/.pyenv/versions/miniconda3-4.7.12/envs/nlp100cc-py3.9-new/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so(+0xc86f5b) [0x11873f0dcf5b] c10d::ProcessGroupNCCL::ncclCommWat
chdog()
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xdc253) [0x118783adc253]
/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x1187c1694ac3]
/lib/x86_64-linux-gnu/libc.so.6(+0x126850) [0x1187c1726850]

*** SIGABRT received at time=1725591384 on cpu 21 ***
PC: @     0x1187c16969fc  (unknown)  pthread_kill
    @     0x1187c1642520  (unknown)  (unknown)
[2024-09-06 11:56:24,098 E 3922458 3925635] logging.cc:440: *** SIGABRT received at time=1725591384 on cpu 21 ***
[2024-09-06 11:56:24,098 E 3922458 3925635] logging.cc:440: PC: @     0x1187c16969fc  (unknown)  pthread_kill
[2024-09-06 11:56:24,099 E 3922458 3925635] logging.cc:440:     @     0x1187c1642520  (unknown)  (unknown)
Fatal Python error: Aborted

run_generation.sh: 2 行: 3922458 中止                  CUDA_LAUNCH_BLOCKING=1 python generation.py -m meta-llama/Llama-2-7b-hf -a activation_mask/LLaMA-2-7B.neuron.pth
```

**Comment by StevenTang1998** [comment]
你可以尝试检查一下torch版本和vllm是否兼容，以及你是否给vllm正确传入了文本而不是id。

**Comment by waterluck** [comment]
谢谢！ 好像是环境配置有问题，改成只用一个gpu的话可以跑了。
另外论文的case study里同时deactivate 语言A和activate B部分的代码可以公开一下吗？ 谢谢。
